name: Build and Test on Linux Mac and Windows

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: Test on ${{ matrix.config.os }} with ${{ matrix.config.cc }}
    runs-on: ${{ matrix.config.os }}
    env:
      CC: ${{ matrix.config.cc }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: ubuntu-latest, cc: "gcc", cxx: "g++"}
        - {os: ubuntu-latest, cc: "clang", cxx: "clang++"}

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies (Linux/macOS)
        run: |
          sudo apt-get update || true
          sudo apt-get install -y cmake build-essential clang
          cmake --version
          clang --version

      - name: Info
        run: echo ${{ github.ref }}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} -V
